sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.1
before_install:
  - gem update bundler
script:
  - bundle install
  - bundle exec rake
env:
  matrix:
    - ENABLE_MYSQL_AWESOME=0 ENABLE_MIGRATION_COMMENTS=0
    - ENABLE_MYSQL_AWESOME=1 ENABLE_MIGRATION_COMMENTS=0
    - ENABLE_MYSQL_AWESOME=0 ENABLE_MIGRATION_COMMENTS=1
    - ENABLE_MYSQL_AWESOME=1 ENABLE_MIGRATION_COMMENTS=1
    - POSTGRESQL=1
addons:
  postgresql: "9.4"
