name: test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
          - "4.0"
        env:
          - MYSQL57
          - MYSQL80
          - POSTGRESQL
          - TRILOGY
        gemfile:
          - activerecord_6.1.gemfile
          - activerecord_7.0.gemfile
          - activerecord_7.1.gemfile
          - activerecord_7.2.gemfile
          - activerecord_8.0.gemfile
          - activerecord_8.1.gemfile
          - activerecord_8.2.gemfile
        exclude:
          # TRILOGY
          - gemfile: activerecord_6.1.gemfile
            env: TRILOGY
          - gemfile: activerecord_7.0.gemfile
            env: TRILOGY
          # activerecord 6.1
          - ruby: "3.3"
            gemfile: activerecord_6.1.gemfile
          - ruby: "3.4"
            gemfile: activerecord_6.1.gemfile
          - ruby: "4.0"
            gemfile: activerecord_6.1.gemfile
          # activerecord 7.0
          - ruby: "3.3"
            gemfile: activerecord_7.0.gemfile
          - ruby: "3.4"
            gemfile: activerecord_7.0.gemfile
          - ruby: "4.0"
            gemfile: activerecord_7.0.gemfile
          # activerecord 7.2
          - ruby: "2.7"
            gemfile: activerecord_7.2.gemfile
          - ruby: "3.0"
            gemfile: activerecord_7.2.gemfile
          # activerecord 8.0
          - ruby: "2.7"
            gemfile: activerecord_8.0.gemfile
          - ruby: "3.0"
            gemfile: activerecord_8.0.gemfile
          - ruby: "3.1"
            gemfile: activerecord_8.0.gemfile
          # activerecord 8.1
          - ruby: "2.7"
            gemfile: activerecord_8.1.gemfile
          - ruby: "3.0"
            gemfile: activerecord_8.1.gemfile
          - ruby: "3.1"
            gemfile: activerecord_8.1.gemfile
          # activerecord 8.2
          - ruby: "2.7"
            gemfile: activerecord_8.2.gemfile
          - ruby: "3.0"
            gemfile: activerecord_8.2.gemfile
          - ruby: "3.1"
            gemfile: activerecord_8.2.gemfile
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ruby/setup-ruby@ae195bbe749a7cef685ac729197124a48305c1cb # v1.276.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup services
        run: |
          for i in {1..60}; do docker compose up -d --quiet-pull && break; sleep 1; done
          # Wait until database servers start
          function mysql57_ping { mysqladmin -u root -h 127.0.0.1 -P 13316 ping; }
          function mysql80_ping { mysqladmin -u root -h 127.0.0.1 -P 13318 ping; }
          function pg_ping { PGPASSWORD=password pg_isready -U postgres -h 127.0.0.1 -p 15442; }
          for i in {1..60}; do mysql57_ping && break; sleep 1; done
          for i in {1..60}; do mysql80_ping && break; sleep 1; done
          for i in {1..60}; do pg_ping && break; sleep 1; done
        env:
          MYSQL_PWD: password
      - name: Run tests
        run: env ${{ matrix.env }}=1 bundle exec rake
        env:
          RUBYOPT: --enable-frozen-string-literal
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: ${{ matrix.ruby }},${{ matrix.gemfile }},${{ matrix.env }}
      - name: Upload test results to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          fail_ci_if_error: true
          flags: ${{ matrix.ruby }},${{ matrix.gemfile }},${{ matrix.env }}
          files: ./junit_format/rspec_xml
      - name: Build and install gem
        run: |
          gem install securerandom -v '~> 0.3.2'
          gem install zeitwerk -v '~> 2.6.18'
          bundle config unset path
          bundle install
          gem build ridgepole.gemspec -o ridgepole.gem
          gem install ridgepole.gem
          ridgepole -v
  finish:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check test conclusion
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs \
          | jq -e '.jobs | map(select(.name | test("^test ")).conclusion) | any(. == "failure") | not'
